### ISSUE TITLE
Use transport in the client, if it is set

### ISSUE THREAD

**Issue by Semior001** [go-pkgz/requester#2]
I have an issue with testing behavior with github.com/google/go-github, as there is no easy way to replace the base URL of the github API to the URL of the test server.

For that, I've decided to mock the test server by redirecting requests by replacing RoundTripper in the client, and found that requester replaces the Transport with `http.DefaultTransport` while generating the HTTP client.

I suggest to replace it only if it is not set in the client.

**Comment by umputun** [comment]
This is not a bad thing to have and generally it makes sense. However I don't really get the original problem - as long as your tested code depends on an interface with `Do(req *http.Request) (*http.Response, error)` instead of the final `Requester` you can mock/fake it as you like, unless your test is some sort of integration/functional and not the unit.

**Comment by Semior001** [comment]
Unfortunately go-github requires the direct `http.Client`. Of course, I could define an interface for requester and mock it in tests, but I've thought that it would be simplier just to redirect requests to the test server.

I.e. I didn't implement the client for github API by my own, but used the written one by google, and it, unfortunately, doesn't depend on an interface.
